language: crystal

before_install:
  - git clone https://github.com/google/gumbo-parser
  - cd gumbo-parser
  - ./autogen.sh
  - ./configure
  - make
  - sudo make install
  - sudo ldconfig

# Uncomment the following if you'd like Travis to run specs and check code formatting
# script:
#   - crystal spec
#   - crystal tool format --check
